name: Build and Deploy to Same Branch

on:
  push:
    branches:
      - feature/css-add

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Move dist content to root
        run: |
          cp -r dist/* .
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f index.html assets/
          git commit -m "Auto-deploy: move dist to root for GitHub Pages" || echo "No changes to commit"
          git push origin feature/css-add

